### ISSUE TITLE
Fix build on node 0.10.x

### ISSUE THREAD

**Issue by tptee** [FormidableLabs/radium-constraints#13]
Relevant Travis logs:

```
ERROR in ./src/layout-client.js
Module build failed: TypeError: /home/travis/build/FormidableLabs/radium-constraints/src/layout-client.js: undefined is not a function
    at exports.default (/home/travis/build/FormidableLabs/radium-constraints/node_modules/babel-plugin-webpack-loaders/lib/runWebPackSync.js:41:51)
    at PluginPass.StringLiteral (/home/travis/build/FormidableLabs/radium-constraints/plugins/lib/babel-plugin-inline-worker.js:41:59)
    at newFn (/home/travis/build/FormidableLabs/radium-constraints/node_modules/babel-traverse/lib/visitors.js:262:19)
    at NodePath._call (/home/travis/build/FormidableLabs/radium-constraints/node_modules/babel-traverse/lib/path/context.js:63:18)
    at NodePath.call (/home/travis/build/FormidableLabs/radium-constraints/node_modules/babel-traverse/lib/path/context.js:47:17)
    at NodePath.visit (/home/travis/build/FormidableLabs/radium-constraints/node_modules/babel-traverse/lib/path/context.js:93:12)
    at TraversalContext.visitQueue (/home/travis/build/FormidableLabs/radium-constraints/node_modules/babel-traverse/lib/context.js:152:16)
    at TraversalContext.visitMultiple (/home/travis/build/FormidableLabs/radium-constraints/node_modules/babel-traverse/lib/context.js:110:17)
    at TraversalContext.visit (/home/travis/build/FormidableLabs/radium-constraints/node_modules/babel-traverse/lib/context.js:182:19)
    at Function.traverse.node (/home/travis/build/FormidableLabs/radium-constraints/node_modules/babel-traverse/lib/index.js:135:17)
    at NodePath.visit (/home/travis/build/FormidableLabs/radium-constraints/node_modules/babel-traverse/lib/path/context.js:103:22)
    at TraversalContext.visitQueue (/home/travis/build/FormidableLabs/radium-constraints/node_modules/babel-traverse/lib/context.js:152:16)
    at TraversalContext.visitMultiple (/home/travis/build/FormidableLabs/radium-constraints/node_modules/babel-traverse/lib/context.js:110:17)
    at TraversalContext.visit (/home/travis/build/FormidableLabs/radium-constraints/node_modules/babel-traverse/lib/context.js:182:19)
    at Function.traverse.node (/home/travis/build/FormidableLabs/radium-constraints/node_modules/babel-traverse/lib/index.js:135:17)
    at NodePath.visit (/home/travis/build/FormidableLabs/radium-constraints/node_modules/babel-traverse/lib/path/context.js:103:22)
 @ ./src/constraint-layout.js 34:216-242
```

Has something to do with our little Frankenstein Babel plugin.
